/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerCard: typeof import('./src/components/AnswerCard.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    NewAnswerDialog: typeof import('./src/components/NewAnswerDialog.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
